import AuthorityHeader from '../../components/authority/AuthorityHeader'
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/card'
import { FileText, Download, Calendar, BarChart2, TrendingUp, AlertTriangle } from 'lucide-react'
import { Button } from '../../components/ui/button'
import { mockWards, mockOverviewStats } from '../../data/mockData'
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  RadarChart, PolarGrid, PolarAngleAxis, Radar,
} from 'recharts'

const reportTypes = [
  { id: 'monthly', title: 'Monthly Infrastructure Report', description: 'Comprehensive overview of infrastructure condition and maintenance activities', icon: BarChart2, generated: '2024-01-15' },
  { id: 'water', title: 'Water Stress Analysis Report', description: 'Ward-wise water supply vs demand analysis with AI predictions', icon: TrendingUp, generated: '2024-01-14' },
  { id: 'risk', title: 'City Risk Assessment Report', description: 'AI-generated composite risk scores for all wards with recommended priorities', icon: AlertTriangle, generated: '2024-01-13' },
  { id: 'complaints', title: 'Citizen Complaint Summary', description: 'Categorized complaint analysis with resolution statistics', icon: FileText, generated: '2024-01-12' },
]

const wardRiskData = mockWards.slice(0, 10).map(w => ({
  ward: w.name.replace('Ward ', 'W'),
  risk: w.riskScore,
  fill: w.riskScore >= 76 ? '#ef4444' : w.riskScore >= 51 ? '#f97316' : w.riskScore >= 26 ? '#f59e0b' : '#22c55e',
}))

const radarData = [
  { subject: 'Road', A: 72, fullMark: 100 },
  { subject: 'Water', A: 58, fullMark: 100 },
  { subject: 'Flood', A: 45, fullMark: 100 },
  { subject: 'Power', A: 38, fullMark: 100 },
  { subject: 'Complaints', A: 64, fullMark: 100 },
  { subject: 'Construction', A: 32, fullMark: 100 },
]

export default function ReportsPage() {
  return (
    <div className="flex-1 overflow-y-auto dark-scroll" style={{ background: '#0a0f1e' }}>
      <AuthorityHeader title="Reports" subtitle="AI-generated municipal intelligence reports — not official government documents" />

      <div className="p-6 space-y-6">
        {/* Disclaimer */}
        <div className="rounded-lg p-3 flex items-start gap-2 border" style={{ background: 'rgba(251,191,36,0.08)', borderColor: 'rgba(251,191,36,0.25)' }}>
          <AlertTriangle size={14} className="text-yellow-400 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-yellow-300">
            All reports are generated by AI models and represent prioritization tools only. They do not constitute official government assessments, legal determinations, or verified infrastructure data. Always validate AI outputs with ground-truth information.
          </p>
        </div>

        {/* Available Reports */}
        <div>
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">Available Reports</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {reportTypes.map(report => {
              const Icon = report.icon
              return (
                <Card key={report.id} className="hover:border-blue-700/50 transition-colors cursor-pointer group">
                  <div className="flex items-start gap-4">
                    <div className="w-10 h-10 rounded-lg bg-blue-900/50 flex items-center justify-center flex-shrink-0 group-hover:bg-blue-700/40 transition-colors">
                      <Icon size={18} className="text-blue-400" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-semibold text-white">{report.title}</div>
                      <div className="text-xs text-slate-400 mt-1">{report.description}</div>
                      <div className="flex items-center gap-3 mt-3">
                        <div className="flex items-center gap-1 text-xs text-slate-500">
                          <Calendar size={10} />
                          Last generated: {report.generated}
                        </div>
                        <Button size="sm" variant="secondary" className="gap-1.5">
                          <Download size={12} />
                          Download PDF
                        </Button>
                        <Button size="sm" variant="ghost">
                          View
                        </Button>
                      </div>
                    </div>
                  </div>
                </Card>
              )
            })}
          </div>
        </div>

        {/* Charts */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Ward Risk Score Distribution</CardTitle>
              <span className="text-xs text-slate-600">AI-generated scores</span>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={220}>
                <BarChart data={wardRiskData} margin={{ top: 4, right: 8, bottom: 4, left: -20 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#1e3a8a22" />
                  <XAxis dataKey="ward" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                  <YAxis tick={{ fill: '#94a3b8', fontSize: 11 }} domain={[0, 100]} />
                  <Tooltip
                    contentStyle={{ background: '#0d1426', border: '1px solid #1e3a8a50', borderRadius: 8, color: '#fff' }}
                    formatter={(v: unknown) => [`${v} / 100`, 'Risk Score']}
                  />
                  <Bar dataKey="risk" radius={[3, 3, 0, 0]}>
                    {wardRiskData.map((entry, i) => (
                      <rect key={i} fill={entry.fill} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>City Risk Profile (Radar)</CardTitle>
              <span className="text-xs text-slate-600">Multi-dimensional risk factors</span>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={220}>
                <RadarChart data={radarData}>
                  <PolarGrid stroke="#1e3a8a40" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                  <Radar name="Risk" dataKey="A" stroke="#3b82f6" fill="#3b82f6" fillOpacity={0.2} strokeWidth={2} />
                  <Tooltip
                    contentStyle={{ background: '#0d1426', border: '1px solid #1e3a8a50', borderRadius: 8, color: '#fff' }}
                  />
                </RadarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </div>

        {/* Summary Stats */}
        <Card>
          <CardHeader>
            <CardTitle>Executive Summary Metrics</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { label: 'Overall City Risk Score', value: mockOverviewStats.overallRiskScore, unit: '/ 100', color: '#f97316' },
                { label: 'Open Citizen Complaints', value: mockOverviewStats.openComplaints, unit: '', color: '#f59e0b' },
                { label: 'Critical Wards', value: 3, unit: ' wards', color: '#ef4444' },
                { label: 'Resolved This Month', value: 1247, unit: ' issues', color: '#22c55e' },
              ].map(stat => (
                <div key={stat.label} className="p-4 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(30,58,138,0.2)' }}>
                  <div className="text-2xl font-bold" style={{ color: stat.color }}>
                    {stat.value.toLocaleString('en-IN')}{stat.unit}
                  </div>
                  <div className="text-xs text-slate-400 mt-1">{stat.label}</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
