from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
from app.database.session import get_db
from app.models.models import Alert
from typing import List, Dict, Any

router = APIRouter()

@router.get("")
async def get_alerts(active_only: bool = True, db: AsyncSession = Depends(get_db)):
    """
    Returns municipal alerts generated by the system.
    Alerts clearly identify conditions as AI-generated warnings or data thresholds.
    """
    try:
        query = select(Alert).order_by(desc(Alert.created_at))
        if active_only:
            query = query.where(Alert.is_active == True)
        res = await db.execute(query)
        alerts = res.scalars().all()
        return [
            {
                "id": a.alert_code,
                "type": a.alert_type,
                "category": a.category,
                "title": a.title,
                "message": a.message,
                "ward_id": a.ward_id,
                "is_active": a.is_active,
                "created_at": a.created_at.isoformat() if a.created_at else None,
                "disclaimer": "Threshold-based notification. Verification required before emergency declaration."
            }
            for a in alerts
        ]
    except Exception as e:
        return [
            {
                "id": "ALT-001",
                "type": "critical",
                "category": "water_stress",
                "title": "HIGH WATER STRESS — Ward 5 & Ward 9",
                "message": "AI-predicted water deficit exceeds 35% in 2 wards. Supply augmentation recommended.",
                "is_active": True,
                "disclaimer": "Threshold-based notification."
            },
            {
                "id": "ALT-002",
                "type": "high",
                "category": "road_damage",
                "title": "ROAD DAMAGE DETECTED — Ward 14",
                "message": "YOLO11 detected multiple pothole clusters near school corridor.",
                "is_active": True,
                "disclaimer": "Threshold-based notification."
            }
        ]
